version: "3"

services:
  express-docker-test:
    image: "docker-node:B${BUILD_NUMBER}"
    build:
      context: .
    command: npm start
    volumes:
      - .:/var/www/express-docker-test
    ports:
      - "0.0.0.0:3001:3001"
      - "0.0.0.0:27017:27017"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "cachdb"
      - "db"
    links:
      - db
      - cachdb
 
  cachdb:
    image: redis:alpine
    container_name: cachdb
    ports: ["6379"]
    networks:
      - back-tier
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - "db-data:/data/db"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: